services:
  - type: web
    name: parth-hospital-backend
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
